### PR TITLE
use unminified code for development build

### PR DESCRIPTION
**Pull request by kellyselden**

### CODE REVIEW

**Comment by kellyselden** [comment]
Here it is finally. Noticed this when stepping through the callstack when debugging locally.

Don't know how testable it is.

**Comment by jasonmit** [comment]
LGTM, as for testing unsure how to go about testing addon models.  I'll try and think about that..

**Comment by jasonmit** [comment]
Versioned as 2.1.0

**Comment by kellyselden** [comment]
Thanks for the quick publish!

**Pull request merged**
