### PR TITLE
fix fastboot support

### PR DESCRIPTION
**Pull request by kellyselden**
I needed this to get moment in fastboot working. Was it ever working before, or is this unnecessary?

### CODE REVIEW

**Comment by jasonmit** [comment]
It was definitely working, use it in a few production apps. I'll have to bisect to figure out at what point it stopped working.

Have you tried going back to the first commit with fastboot support?

**Comment by jasonmit** [comment]
I think this happened around your previous includeTimezone change since that contains the momentjs module as well as timezone data.  I believe it's harmless to include the full timezone data for fastboot builds since payload size isn't much of a concern.

**Comment by kellyselden** [comment]
Oh I didn't realize that original fastboot import had the entire payload. I'll look at the code again and see if I can salvage this PR or not.

**Comment by jasonmit** [comment]
Even trolled me so perhaps we rename it the file or add a comment for the future

**Comment by kellyselden** [comment]
I think I salvaged it. I think it makes sense to respect the same option `includeTimezone` in fastboot, even though it doesn't affect asset size. If not for correctness, then to gain minor speed benefit of only requiring one file instead of two.

**Comment by jasonmit** [comment]
I wonder how this will work with locale data and if it's bundled or not in that bundle.  Could be an existing bug though, I can hopefully verify tonight.

**Comment by jasonmit** [comment]
Didn't mean to close :)

**Comment by jasonmit** [comment]
LGTM, I'll investigate the locale data and fix that in a separate PR if it is indeed an issue.  Once I verify I'll version.

**Comment by jasonmit** [comment]
Everything you've worked on is versioned under 2.2.0

**Pull request merged**
