### PR TITLE
Consolidate Fastboot shims

### LINKED ISSUE #154: Issue with new fastboot ember-engines support
when working with the new fastboot support for ember-engines (https://github.com/ember-engines/ember-engines/pull/494) ember-cli-moment-shim is throwing the following error: `TypeError: Cannot set property 'compare' of undefined`

It looks like this is referring to here: https://github.com/jasonmit/ember-cli-moment-shim/blob/master/addon/index.js

I've been sleuthing through the trees, and I'm not sure I fully get how this library is being handled in Fastboot using the manifest generated files.  I see some PRs for engines, and others for fastboot, but anyone familiar with both together?

### PR DESCRIPTION
**Pull request by thec0keman**
Consolidate the import shims of fastboot into the main addon.  This should fix #154 

It looks as if in fastboot, both the `addon/lib` and public files were both being evaluated, and the addon one was taking precedence.  This resulted in errors like `Cannot set property `compare` of undefined`.

I've tested this in both fastboot and the browser, both with timezone and without.

### CODE REVIEW

**Comment by jasonmit** [comment]
This seems reasonable and thank you for taking the time to tackle this.  Any chance we can add fastboot tests?  Way back when the fastboot story was non existent, unsure if that has changed recently.  If it's still complicated then I'm fine with moving forward as-is.

**Review by jasonmit — APPROVED** [review]

**Comment by thec0keman** [comment]
Took a stab at some tests

**Comment by iamareebjamal** [comment]
Interestingly, it was working well for us before in fastboot, but now it throws `Cannot set property 'compare' of undefined` after this release

**Comment by scottmessinger** [comment]
We're also running into `TypeError: Cannot set property 'compare' of undefined`. Not sure the cause yet.

**Comment by scottmessinger** [comment]
Appears to be an issue upgrading from 3.7.1 to 3.8.0 and running in fastboot.

**Comment by jasonmit** [comment]
As far as I understand, Fastboot was broken and is now fixed except for the [`compare`](https://github.com/jasonmit/ember-cli-moment-shim/blob/master/addon/index.js#L3-L22) proto extension (`compare` was/is needed so things like `Ember.computed.sort` work) now missing.  If none of that's true, we can probably just revert this this PR and move on.

In short, I really dislike how we've extended the proto of `moment` to support this Ember features.

Reason being - in the future, the `compare` method will no longer exist once we migrate off this addon to a `ember-auto-import`/`webpack` plugin solution - so we should think about a world where we make it work without this patch.

Perhaps there's a better solution?  I don't use Ember or moment anymore in my day job (unfortunately, because I really miss it) - so it's unlikely I'll get around to patching this if the fix is beyond just reverting this commit.

Is this issue something someone else wants to take up?  If so, lets open a new issue for tracking since visibility on closed PRs are difficult to find.

**Pull request merged**
