### PR TITLE
update locale folder location

### PR DESCRIPTION
**Pull request by kellyselden**
Looks like that folder isn't plural (anymore?)

screen shot 2016-09-14 at 5 58 06 pm

### CODE REVIEW

**Comment by jasonmit** [comment]
Not the first time they changed the package shape and didn't version as a major.  We might need to support both to allow things to continue to work for those who lock/shrinkwrap their deps.

**Review by jasonmit — COMMENTED** [review]
https://github.com/jasonmit/ember-css-modules/commit/73ae555dd66bd34ef1ed65b75744df1119e7dc9b#diff-e34ff60bd44b7694b75794836ad28518R30

**Comment by jasonmit** [comment]
Wrong window, didn't mean to paste that and now have no idea how to remove it.

In any case, I think in order to be backwards compatible we would need to support both folder structures.

**Comment by jasonmit** [comment]
Actually spent some time looking at this, and `locales/` is valid here because of this funnel:
https://github.com/jasonmit/ember-cli-moment-shim/blob/master/index.js#L166-L176

Is there any issue?

**Comment by kellyselden** [comment]
No issue, I just noticed it when working on my next incoming pull request 😉

**Comment by jasonmit** [comment]
Nice, looking forward to see :)

**Pull request closed without merging**
